"""Offline US city geocoding backed by the US Census Gazetteer.

The gazetteer CSV (routes/data/us_places.csv) is generated by the
`build_gazetteer` management command and committed to the repo, so
geocoding a "City, ST" pair needs no network call.
"""
import csv
import re
from functools import lru_cache
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent.parent / 'data'
GAZETTEER_PATH = DATA_DIR / 'us_places.csv'

US_STATES = frozenset({
    'AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA',
    'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM',
    'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA',
    'WV', 'WI', 'WY',
})

# Census names carry a legal/statistical suffix, e.g. "Tomah city", "Big Cabin town", "Abanda CDP".
_CENSUS_SUFFIX = re.compile(
    r'\s+(city and borough|consolidated government.*|unified government.*|metropolitan government.*'
    r'|urban county|city|town|village|borough|CDP|municipality|township|charter township|plantation'
    r'|CCD|UT|gore|grant|location|purchase|district|precinct|unorganized territory)(\s*\(.*\))?$',
    re.IGNORECASE,
)
_ABBREVIATIONS = [
    (re.compile(r'\bst\.?\s'), 'saint '),
    (re.compile(r'\bste\.?\s'), 'sainte '),
    (re.compile(r'^ft\.?\s'), 'fort '),
    (re.compile(r'^mt\.?\s'), 'mount '),
    (re.compile(r'^s\s'), 'south '),
]


def normalize_place_name(name):
    """Canonical key for a place name: 'St. Louis', 'Saint Louis' and 'SAINT-LOUIS' all match."""
    key = name.lower().strip()
    for pattern, replacement in _ABBREVIATIONS:
        key = pattern.sub(replacement, key)
    return re.sub(r'[^a-z0-9]', '', key)


def census_name_variants(census_name):
    """Keys a Census place may be looked up by.

    'Salt Lake City city' -> 'Salt Lake City' (and 'Salt Lake');
    'Macon-Bibb County' -> also 'Macon'.
    """
    once = _CENSUS_SUFFIX.sub('', census_name)
    return {once, _CENSUS_SUFFIX.sub('', once), once.split('-')[0], once.split('/')[0]}


class Gazetteer:
    def __init__(self, rows):
        self._index = {}
        for state, name, lat, lng in rows:
            for variant in census_name_variants(name):
                # First entry wins: incorporated places are listed before county subdivisions.
                self._index.setdefault((state, normalize_place_name(variant)), (lat, lng))

    @classmethod
    def from_csv(cls, path=GAZETTEER_PATH):
        with open(path, newline='', encoding='utf-8') as fh:
            reader = csv.DictReader(fh)
            return cls((r['state'], r['name'], float(r['lat']), float(r['lng'])) for r in reader)

    def lookup(self, city, state):
        """Return (lat, lng) for a city in a US state, or None."""
        return self._index.get((state.strip().upper(), normalize_place_name(city)))


@lru_cache(maxsize=1)
def get_gazetteer():
    return Gazetteer.from_csv()
