# Generated by Django 6.1.1 on 2026-09-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('rack_id', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=8, help_text='Retail price, USD per gallon', max_digits=12)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('geocode_source', models.CharField(blank=True, choices=[('gazetteer', 'US Census Gazetteer'), ('ors', 'OpenRouteService geocoder')], max_length=16)),
            ],
            options={
                'ordering': ['state', 'city', 'name'],
                'indexes': [models.Index(fields=['state', 'city'], name='routes_fuel_state_34c75b_idx')],
            },
        ),
    ]
